---
- name: Recargar Apache
  ansible.builtin.service:
    name: apache2
    state: reloaded
  listen: servicios_apache

- name: Reiniciar servicio Apache2 y activar
  ansible.builtin.service:
    name: apache2
    state: restarted
    enabled: yes
  listen: servicios_apache