---
- name: Incluye el archivo con las variables
  ansible.builtin.include_vars:
    file: vars_main.yml

- name: Instalacion de dependencias
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: true
    cache_valid_time: 3600
  with_items: "{{ sspr_packages }}"

- name: Importar llave
  ansible.builtin.apt_key:
    url: https://ltb-project.org/wiki/lib/RPM-GPG-KEY-LTB-project
    state: present

- name: Agregar repo
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://ltb-project.org/debian/stable stable main
    state: present
    update_cache: true

- name: Instalacion de aplicacion SSPR
  ansible.builtin.apt:
    name: [ 'self-service-password' ]

- name: copiando archivos de configuracion
  ansible.builtin.copy:
    src: "{{ item.origen }}"
    dest: "{{ item.destino }}"
    owner: root
    group: root
    mode: 0775
    backup: true
  with_items:
    - { origen: 'self-service-password.conf', destino: '/etc/apache2/sites-available/' }
    - { origen: 'config.inc.local.php', destino: '/usr/share/self-service-password/conf/' }
    - { origen: 'logo.png', destino: '/usr/share/self-service-password/htdocs/images/' }

- name: Generando llave openSSL
  ansible.builtin.openssl_privatekey:
    path: "/etc/ssl/private/{{ server_hostname }}.key"
    size: "{{ key_size }}"
    type: "{{ key_type }}"

- name: Generando CSR
  ansible.builtin.openssl_csr:
    path: "/etc/ssl/private/{{ server_hostname }}.csr"
    privatekey_path: "/etc/ssl/private/{{ server_hostname }}.key"
    country_name: "{{ country_name }}"
    organization_name: "{{ organization_name }}"
    email_address: "{{ email_admins }}"
    common_name: "{{ server_hostname }}"

- name: Generando certificado autofirmando con openSSL
  ansible.builtin.openssl_certificate:
    path: "/etc/ssl/certs/{{ server_hostname }}.crt"
    privatekey_path: "/etc/ssl/private/{{ server_hostname }}.key"
    csr_path: "/etc/ssl/private/{{ server_hostname }}.csr"
    provider: selfsigned

- name: Activando UFW
  ansible.builtin.ufw:
    state: enabled
    logging: true

- name: Abriendo puertos HTTPS + SSH
  ansible.builtin.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  with_items:
    - "{{ ssh | int }}"
    - "{{ https | int }}"

- name: Activando el sitio
  ansible.builtin.command: "/usr/sbin/a2ensite {{ sitio_conf }}"

- name: Instalar modulo SSL
  ansible.builtin.command: "/usr/sbin/a2enmod ssl"
  notify: servicios_apache

