---
- include_vars: ../../vars_main.yml

- include_tasks: ../../dep_check.yml

- name: Agregando al usuario "{{ uid }}" a unidad organizativa "{{ ou }}"
  ldap_entry:
    dn: "uid={{ uid }},ou={{ ou }},dc={{ base }}"
    objectClass:
      - top
      - person
      - organizationalPerson
      - inetOrgPerson
    attributes:
      cn: "{{ cn }}"
      sn: "{{ sn }}"
      mail: "{{ uid }}@cultura.lab"
      uid: "{{ uid }}"
      title: "{{ attr_usuarios }}"
      street: "{{ attr_usuarios }}"
    state: present
  args: "{{ ldap_auth }}"

- name: Generando el password
  ldap_passwd:
    dn: "uid={{ uid }},ou={{ ou }},dc={{ base }}"
    passwd: "{{ password }}"
  args: "{{ ldap_auth }}"