---
- name: Incluye el archivo con las variables
  ansible.builtin.include_vars:
    file: vars_main.yml

- name: Instalacion de dependencias
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: true
    cache_valid_time: 3600
  with_items: "{{ sspr_packages }}"

- name: Importar llave
  ansible.builtin.apt_key:
    url: "{{ sspr_key }}"
    state: present

- name: Agregar repo
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] {{ sspr_repo }} stable main"
    state: present
    update_cache: true

- name: Instalacion de aplicacion SSPR
  ansible.builtin.apt:
    name: [ 'self-service-password' ]

- name: copiando archivos de configuracion
  ansible.builtin.template:
    src: "{{ item.origen }}"
    dest: "{{ item.destino }}"
    owner: root
    group: root
    mode: 0644
    backup: true
  with_items:
    - { origen: 'files/self-service-password.conf.j2', destino: '/etc/apache2/sites-available/{{ sitio_conf }}' }
    - { origen: 'files/config.inc.local.php.j2', destino: '/usr/share/self-service-password/conf/{{ app_conf }}' }

- name: copiando archivos
  ansible.builtin.copy:
    src: "{{ item.origen }}"
    dest: "{{ item.destino }}"
    owner: root
    group: root
    mode: 0644
    backup: true
  with_items:
    - { origen: 'files/logo.png', destino: '/usr/share/self-service-password/htdocs/images/logo.png' }

- name: Generando llave openSSL
  ansible.builtin.openssl_privatekey:
    path: "/etc/ssl/private/{{ server_hostname }}.key"
    size: "{{ key_size }}"
    type: "{{ key_type }}"

- name: Generando CSR
  ansible.builtin.openssl_csr:
    path: "/etc/ssl/private/{{ server_hostname }}.csr"
    privatekey_path: "/etc/ssl/private/{{ server_hostname }}.key"
    country_name: "{{ country_name }}"
    organization_name: "{{ organization_name }}"
    email_address: "{{ email_admins }}"
    common_name: "{{ server_hostname }}"

- name: Generando certificado autofirmando con openSSL
  ansible.builtin.openssl_certificate:
    path: "/etc/ssl/certs/{{ server_hostname }}.crt"
    privatekey_path: "/etc/ssl/private/{{ server_hostname }}.key"
    csr_path: "/etc/ssl/private/{{ server_hostname }}.csr"
    provider: selfsigned

- name: Eliminando index.html
  ansible.builtin.file:
    path: /var/www/html/index.html
    state: absent

- name: Activa Apache mods
  ansible.builtin.apache2_module:
    state: present
    name: "{{ item }}"
  with_items: "{{ apache_mods }}"

- name: Desactivando sitio por default 
  ansible.builtin.command: a2dissite 000-default

- name: Activando UFW
  ansible.builtin.ufw:
    state: enabled
    logging: true

- name: Abriendo puertos HTTPS + SSH
  ansible.builtin.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  with_items:
    - "{{ ssh | int }}"
    - "{{ https | int }}"
    - "{{ http | int }}"

- name: Activando el sitio
  ansible.builtin.command: /usr/sbin/a2ensite {{ sitio_conf }}
  notify: servicios_apache

